### ISSUE TITLE
The type or namespace name 'TensorFlow' could not be found

### ISSUE THREAD

**Issue by oddEventHorizon** [Unity-Technologies/ml-agents#1511]
Hi,

I've stumbled upon this problem when trying to experiment with ML Agents. I have noticed that few other people got stuck on it as well but none of them has really replied here with a solution that would help in my case or replied with any solution at all.

ISSUE:
When I put "ENABLE_TENSORFLOW" into the Scripting Define Symbols fields my VS Code is getting red all over the "using Tensorflow;" in TFSharpInferenceEngine.cs

Screenshot:
![image](https://user-images.githubusercontent.com/19377008/50259567-e6331b00-0404-11e9-8b7e-a94553c498ea.png)

My setup:
ML Agents: v0.6 - had the same problem on v0.5 as well
Unity version: 2018.3.0f2 (official) - had this issue on 2018.3.0f1 (beta) as well 
TF : 1.12
Python: 3.6.7
VS Code: 1.3 with: C#, Debugger for Unity, Unity Tools plugins. 
.NET Frameworks: (perhaps I have too many of them)? 
![image](https://user-images.githubusercontent.com/19377008/50260030-ed5b2880-0406-11e9-8eee-6ffab982d929.png)
Project Settings:
![image](https://user-images.githubusercontent.com/19377008/50260082-272c2f00-0407-11e9-80a9-b9c2dfead731.png)
I installed TFSharpPlugin (by double clicking it. And I keep it in a different folder than Unity if it made any difference... i'm becoming paranoid.. :))

I confirmed to have this issue on both of my projects (started new, clean one as well) 

Any suggestions would be greatly appreciated. Thanks!

**Comment by 13Flo** [comment]
As described [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md), make sure you installed that one:
https://s3.amazonaws.com/unity-ml-agents/0.5/TFSharpPlugin.unitypackage

That could be the source of your issue.

**Comment by oddEventHorizon** [comment]
> As described [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md), make sure you installed that one:
> https://s3.amazonaws.com/unity-ml-agents/0.5/TFSharpPlugin.unitypackage
> 
> That could be the source of your issue.

Thanks for the reply, but I have installed TFSharpPlugin. I described it here in my initial post: 

"I installed TFSharpPlugin (by double clicking it. And I keep it in a different folder than Unity if it made any difference... i'm becoming paranoid.. :))"

**Comment by 13Flo** [comment]
Just wanted to make sure we both installed the same ;)

Also, I can confirm it doesn't make any difference to keep the
.unitypackage inside or outside of the project folder.

One difference I can see with my (working) project is the API compatibility
level in Player Settings. Mine is set to ".Net Standard 2.0" (while yours
seems to be set to ".Net 4")

**Comment by louis030195** [comment]
I had this issue migrating from 0.5 to 0.6, and fixed it by reimporting TFsharp (on Ubuntu import package -> custom package) and it's located in Assets/Plugin
Where is your tfsharp imported ?

**Comment by awjuliani** [comment]
Hi @oddEventHorizon 

Do you get errors in the Unity Editor, or just in VS Code?

**Comment by oddEventHorizon** [comment]
> Hi @oddEventHorizon
> 
> Do you get errors in the Unity Editor, or just in VS Code?

Hi.
No. Zero errors in Unity. I can even hit play button in one of the examples you've provided and game starts to simulate. 

I have been trying desperately to find what broke it and potential workaround that I've came up with this.

When mentioned issue occurs in VS Code about tensorflow namespace or type not found, I open my Visual Studio 2017 Community. I open my project solution properties and I change: 

**Target Framework** from: **.NET Framework 4.5** to: **.NET Framework 4.6.1**

Then I go back to VS Code and all the compilation errors are gone. However If I close VS Code (that had no issues at the moment of closing) and I reopen it with Unity->Assets->Open C# Project - the problem occurs again. 

**It seems as if Unity was forcing .NET Framework 4.5 for some reason.** 

However as much as I'm happy that I have found a workaround I doubt it's a proper solution and I assume there my be some mistake that I'm making.

**Comment by 13Flo** [comment]
That could be a good occasion to switch to [Jetbrains Rider](https://www.jetbrains.com/rider/)... ;)

**Comment by oddEventHorizon** [comment]
@13Flo : yeah, but the price :)

**Comment by oddEventHorizon** [comment]
Update:

I have noticed that until I change .NET Framework via Visual Studio Community 2017 I'm getting this printed out in the OmniSharp Log output window:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): Error: The primary reference "TensorFlowSharp" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): Error: The primary reference "System.Interactive.Async" could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".`

I also almost certain that this issue **was not occuring on Unity 2017** where I was able to specifically pick which .NET Framework 4.6 from the Scripting Runtime Version field in the Project Settings. In Unity 2018 you can only specify .NET Framework 4.x (equivalent). Maybe it's hardcoded to 4.5 somewhere?

**Comment by xiaomaogy** [comment]
@awjuliani

**Comment by awjuliani** [comment]
We have replaced TF# with our internal inference solution as of v0.7. Closing this issue for now. Please feel free to re-open if you deem it necessary.

**Comment by weiweitoo** [comment]
@awjuliani I am using the v0.7 ml-agent, and unity 2018.3.11. Still facing the issue the same issue. 
![image](https://user-images.githubusercontent.com/25069837/55543957-a9add580-56fc-11e9-9914-2ab5be0e7448.png)

Step to reproduce the setup
1. Do the same project configuration
![image](https://user-images.githubusercontent.com/25069837/55543881-8420cc00-56fc-11e9-868d-1671c100a479.png)
2. Import from ml-agent/UnitySDK/Assets

**Comment by xiaomaogy** [comment]
Hi @weiweitoo , since we got rid of TensorflowSharp, please remove the ENABLE_TENSORFLOW symbol, and it should be working.

**Comment by weiweitoo** [comment]
@xiaomaogy Cool. It works perfectly. Thanks!

**Comment by temptitle** [comment]
Issue still exists 

1. Install Unity 2019.12f1.
2. Copy-past ml-agents from unity ml-agents repo.
3. install tensorflow-sharp
4. Change player settings (with 'ENABLE_TENSORFLOW' and without).


<img width="1042" alt="Screen Shot 2019-05-13 at 1 00 57 PM" src="https://user-images.githubusercontent.com/36921178/57613566-e1236380-757f-11e9-9327-e3c85476bc89.png">
<img width="395" alt="Screen Shot 2019-05-13 at 12 58 22 PM" src="https://user-images.githubusercontent.com/36921178/57613568-e1236380-757f-11e9-8b94-704e7bb3341d.png">
