### ISSUE TITLE
'function' object has no attribute 'num_envs'

### ISSUE THREAD

**Issue by mikiwong** [Unity-Technologies/ml-agents#1835]
Hi,

I am trying to run the unity gym wrapper +baselines example given in the docs using the Banana Collector environment. But I am encountering this error:
'AttributeError: 'function' object has no attribute 'num_envs' 
in line 91, in ppo2.py. 

I am using baselines 0.1.5 and ml-agents 0.7.0

**Comment by ervteng** [comment]
Hi @mikiwong, baselines continuously changes their API, so our guide might indeed be broken. Looking at the code, it looks like you can solve this by simply setting nenvs in `ppo2.py` to the number of environments you're spawning, and not trying to read it from the env object.

**Comment by xiaomaogy** [comment]
Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.

**Comment by ryujaehun** [comment]
I am also encountering the error like ```AttributeError: 'function' object has no attribute 'num_envs'``` when  [gym-unity](https://github.com/Unity-Technologies/ml-agents/tree/master/gym-unity) 
This problem was solved as follows.
```
env=env => env=env()
```

**Comment by qfettes** [comment]
This is still an issue, but has a simple fix. Baselines expects the environments to be wrapped as SubprocessVecEnv or DummyVecEnv. Thus, change the make_unity_env function in the tutorial to:

```
from gym_unity.envs import UnityEnv

from baselines.common.vec_env.subproc_vec_env import SubprocVecEnv
from baselines.common.vec_env.dummy_vec_env import DummyVecEnv
from baselines.bench import Monitor
from baselines import logger
import baselines.ppo2.ppo2 as ppo2

try:
    from mpi4py import MPI
except ImportError:
    MPI = None

def make_unity_env(env_directory, num_env, visual, start_index=0):
    """
    Create a wrapped, monitored Unity environment.
    """
    def make_env(rank, use_visual=True): # pylint: disable=C0111
        def _thunk():
            env = UnityEnv(env_directory, rank, use_visual=use_visual, uint8_visual=True)
            env = Monitor(env, logger.get_dir() and os.path.join(logger.get_dir(), str(rank)))
            return env
        return _thunk
    if visual:
        return SubprocVecEnv([make_env(i + start_index) for i in range(num_env)])
    else:
        rank = MPI.COMM_WORLD.Get_rank() if MPI else 0
        return DummyVecEnv([make_env(rank, use_visual=False)])
```

**Comment by ervteng** [comment]
Hi @qfettes, I think this guidance would help a lot of people - it'd be great if you could make a PR to our `gym_unity` docs so you get credit for the fix :P.  

Also, out of curiosity, which version of Baselines are you using?

**Comment by qfettes** [comment]
Done - I just opened a pull request which fixes the issue.

I just pulled from baselines today, so it's the latest version.
