### ISSUE TITLE
some missing config params in Learning-Environment-Create-New.md

### ISSUE THREAD

**Issue by RobTranquillo** [Unity-Technologies/ml-agents#3959]
**Describe the bug**

I'am on the "release_1" tag and try to get the [Learning-Environment-Create-New](https://github.com/Unity-Technologies/ml-agents/blob/release_1/docs/Learning-Environment-Create-New.md) running.
But in rollerball_config.yaml there are two missing params, Sequence_length and memory_size.
I looked into the other demos and set it to:
-   sequence_length: 64
-  memory_size: 128

I'am also had to change the Behaviour Style from Heuristic to Default. I think that is also missing in that tutorial.

**To Reproduce**

Done the example.

**Console logs / stack traces**
```
mlagents.trainers.exception.UnityTrainerException: The hyper-parameter sequence_length could not be found for the <class 'mlagents.trainers.ppo.trainer.PPOTrainer'> trainer of brain RollerBall.
```
```
mlagents.trainers.exception.UnityTrainerException: The hyper-parameter memory_size could not be found for the <class 'mlagents.trainers.ppo.trainer.PPOTrainer'> trainer of brain RollerBall.
```

**Environment (please complete the following information):**
- Unity Version: 2019.3.11
- Windows 10
-   ml-agents: 0.16.0,
-   ml-agents-envs: 0.16.0,
-   Communicator API: 1.0.0,
-   TensorFlow: 2.2.0

**Comment by DanTulovsky** [comment]
Additionally, please fix:

    reward_signals:
        extrinsic:
        strength: 1.0
        gamma: 0.99

should be:

    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

**Comment by awjuliani** [comment]
Hi all.

This should be fixed now on the last version of `master`. Thanks for calling it out though.

**Comment by DanTulovsky** [comment]
Do you mean in:  https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md ?

I still see the same error:

reward_signals:
    extrinsic:
    strength: 1.0
    gamma: 0.99

**Comment by awjuliani** [comment]
Thanks for pointing this out, @DanTulovsky 

I was thinking of the original issue. What you bring up also needs to be addressed though. I will make a PR to do so right now.

**Comment by chriselion** [comment]
Closing this, as the original issues have been fixed.
