### ISSUE TITLE
AttributeError: 'str' object has no attribute '_key'

### ISSUE THREAD

**Issue by ChristosDav** [Unity-Technologies/ml-agents#5794]
Hello everyone.

I recently run into this issue with a project I've been working on. The problem occurs whenever I'm trying to run the **mlagents-learn** command as it is show in the screenshot below. Note that I followed the installation instructions step by step and had no problem until the training phase.  
I'm using **ml agents release 19**

Thanks a lot in advance!

![error](https://user-images.githubusercontent.com/87013739/193783618-89b5a523-83c6-43fd-bfb3-0814e13f641c.png)

**Comment by reidpat** [comment]
I am also running into the exact same issue.

**Comment by Eelam** [comment]
Hi,
I’m just starting to learn ML-Agents. Since you are using the same version as me, My question is, did you update anything? E.g. ML-Agents in the Unity Package Manager.
Why haven’t you provided the Environment info as the template states?

**Comment by ChristosDav** [comment]
As I mentioned above, I followed the installation guide for the latest release (19). I'm also running this project on a virtual environment with: 
**python version**: 3.9.7 
**ml agents version**: 0.28.0
**upgraded pip**: 22.2.2
and everything else as default as the guide provided here. Also I haven't updated the package so currently I'm running on **2.2.1 exp.1** . If more detailed information can help solve this issue tell me and I'll upload more screenshots.

![ML-Agents package](https://user-images.githubusercontent.com/87013739/193944844-51a0b88a-b822-4d04-a206-ca5ef54a6dd4.jpg)
![virtual env](https://user-images.githubusercontent.com/87013739/193945076-1401f918-61d4-4be1-8cec-5aeeedd79363.jpg)
![Project folder](https://user-images.githubusercontent.com/87013739/193945089-e459f467-3a1f-4168-bb80-3f0ce743f290.jpg)

**Comment by LeoT1** [comment]
I have this exact same issue

**Comment by LeezPayne** [comment]
It seems that  ml-agents  depends on the old importlib-metadata library. I solved this problem by ` pip install importlib-metadata==4.4`

**Comment by LeoT1** [comment]
did the install it works now !

**Comment by ChristosDav** [comment]
I also found another solution which is upgrading python. I've installed python version 3.8.10, run the hole installation process from the beginning and everything works just fine now!
So I guess we have two different solutions to the problem, that's cool!

**Comment by Kuriboh2017** [comment]
> It seems that `ml-agents` depends on the old `importlib-metadata` library. I solved this issue by ` pip install importlib-metadata==4.4`

I have the same problem and this is useful for me.

**Comment by miguelalonsojr** [comment]
Either method works. Thanks for the fix! We're considering bumping the minimum supported version of python to 3.8.x, which should fix the issue.

**Comment by visuallization** [comment]
> pip install importlib-metadata==4.4

Thanks you saved me a lot of headache!

**Comment by Moo-Cow-News** [comment]
I still have the same problem and I have tried your solution @LeezPayne. 
![image](https://user-images.githubusercontent.com/68777530/200382151-7d336a32-aa76-4797-b280-05a4e9ced723.png)

**Comment by Nana1330** [comment]
> It seems that  `ml-agents` depends on the old `importlib-metadata` library. I solved this issue by ` pip install importlib-metadata==4.4`

This worked for me. I changed the metadata version to 4.8.0 and it worked.

**Comment by Nana1330** [comment]
> I still have the same problem and I have tried your solution @LeezPayne. 
> ![image](https://user-images.githubusercontent.com/68777530/200382151-7d336a32-aa76-4797-b280-05a4e9ced723.png)
> 

Try changing the metadata version to 4.8

**Comment by Moo-Cow-News** [comment]
Thank you, @Nana1330! That solution worked!
