### ISSUE TITLE
Error with numpy while installing mlagents

### ISSUE THREAD

**Issue by trishaladabala** [Unity-Technologies/ml-agents#6122]
<img width="1311" alt="1" src="https://github.com/Unity-Technologies/ml-agents/assets/50787738/6eb96aba-5591-48a4-abcf-e83d6a1117d2">

<img width="1292" alt="2" src="https://github.com/Unity-Technologies/ml-agents/assets/50787738/fd5b8379-79f0-42e3-a174-c5d0ce2a9b39">

<img width="1299" alt="3" src="https://github.com/Unity-Technologies/ml-agents/assets/50787738/8ac73a2a-a4f7-45dd-aa40-a7f946795ce4">

I have attached three photos in the order of the execution and error of my pip install mlagents code. I have been getting this error for so long. Please suggest any alternatives.

**Comment by JuanGdev** [comment]
Hi @trishaladabala this was solved on #6021 . Just download from the develop branch and it should work if you follow the installations instructions

**Comment by JulesVerny** [comment]
So why has this  still not been resolved on the "Stable" Release 21 !
I don't know how to 'Pull Down' the development Branch. I have always used Stable Releases to avoid these issues.

**Comment by thaiminhpv** [comment]
You need to use `python3.9`

This works for me
```bash
conda create --name test python=3.9 
conda activate test
pip install 'numpy==1.26.4'
pip install 'cython<3'
pip install mlagents
pip install protobuf==3.20.*
```

It turned out that python3.10 and python3.11 will try to install `numpy==1.18.5`, which is not possible since it will encounter https://github.com/numpy/numpy/issues/24377
