### ISSUE TITLE
I found an issue with pytorch dependancy

### ISSUE THREAD

**Issue by Nitesh-joestar** [Unity-Technologies/ml-agents#6250]
according to the setup.py of mlagents, it states that it requires a torch version>=2.1.1.
but somewhere along the way. i belive the new pytorch release uses onnxscript to export and save the onnx file. 

here comes the issue:
onnxscript requires onnx>=1.16.0
mlagents requires onnx==1.15.0

they therefore cannot be in the same env without conflicts
every version of onnxscript from the very beginning requires onnx>=1.16

i found that this is a pytorch error because the newest version gives an error when saving. stating that no module named onnxscript is found. whereas pytorch 2.1.1 doesnt throw this error.
can someone update the dependency or tell me if i am wrong

**Comment by maryamziaa** [comment]
Thanks for reporting. Should be fixed in https://github.com/Unity-Technologies/ml-agents/pull/6251

**Comment by danielmanz17** [comment]
was this resolved? I am still unable to resolve this conflict.
