### ISSUE TITLE
Visual Obs App with Internal Brain run via Python Issue

### ISSUE THREAD

**Issue by RossMelbourne** [Unity-Technologies/ml-agents#659]
I need help running a visual observation app with an Internal Brain via python.  The following python code works successfully with 3DBall compiled in internal mode.  However as soon as I run the same python code with the GridWorld app compiled in Internal mode which has Visual Observations (runs in Editor fine), I get the errors seen below:

import numpy as np
from unityagents import UnityEnvironment

env_name = "GridWorld" # Name of the Unity environment binary to launch
train_mode = False # Whether to run the environment in training or inference mode

env = UnityEnvironment(file_name=env_name)

# Set the default brain to work with
default_brain = env.brain_names[0]
brain = env.brains[default_brain]

for episode in range(10):
    env_info = env.reset(train_mode=train_mode)[default_brain]
    done = False

    while not done:
        env_info = env.step()[default_brain]
        done = env_info.local_done[0]

    print("Test ended")

env.close()

INFO:unityagents:
'GridAcademy' started successfully!
Unity Academy name: GridAcademy
        Number of Brains: 1
        Number of External Brains : 0
        Lesson number : 0
        Reset Parameters :
		gridSize -> 5.0
		numObstacles -> 1.0
		numGoals -> 1.0
Unity brain name: GridWorldBrain
        Number of Visual Observations (per agent): 1
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 0
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 
WARNING:unityagents: No External Brains found in the Unity Environment. You will not be able to pass actions to your agent(s).
Traceback (most recent call last):
  File "Inference.py", line 18, in <module>
    env_info = env.step()[default_brain]
  File "/Users/rossmelbourne/ml-agents-master/ml-agents/python/unityagents/environment.py", line 471, in step
    return self._get_state()
  File "/Users/rossmelbourne/ml-agents-master/ml-agents/python/unityagents/environment.py", line 331, in _get_state
    obs_n.append(self._get_state_image(self._brains[b].camera_resolutions[o]['blackAndWhite']))
  File "/Users/rossmelbourne/ml-agents-master/ml-agents/python/unityagents/environment.py", line 234, in _get_state_image
    s = self._process_pixels(image_bytes=s, bw=bw)
  File "/Users/rossmelbourne/ml-agents-master/ml-agents/python/unityagents/environment.py", line 195, in _process_pixels
    image = Image.open(io.BytesIO(s))
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x10d025888>

Also, in the Player Log I see this:

NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Texture:Internal_GetWidth (UnityEngine.Texture)
  at UnityEngine.Texture.get_width () [0x00001] in <4b58939e897a4c34942efe344ae250a9>:0 
  at CoreBrainInternal.BatchVisualObservations (System.Collections.Generic.List`1[T] textures, System.Boolean BlackAndWhite) [0x0000f] in /Users/rossmelbourne/ml-agents-master/ml-agents/unity-environment/Assets/ML-Agents/Scripts/CoreBrainInternal.cs:509 
  at CoreBrainInternal.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) [0x00256] in /Users/rossmelbourne/ml-agents-master/ml-agents/unity-environment/Assets/ML-Agents/Scripts/CoreBrainInternal.cs:222 
  at Brain.DecideAction () [0x0000d] in /Users/rossmelbourne/ml-agents-master/ml-agents/unity-environment/Assets/ML-Agents/Scripts/Brain.cs:241 
  at (wrapper delegate-invoke) <Module>:invoke_void ()
  at Academy.EnvironmentStep () [0x00154] in /Users/rossmelbourne/ml-agents-master/ml-agents/unity-environment/Assets/ML-Agents/Scripts/Academy.cs:477 
  at Academy.FixedUpdate () [0x00002] in /Users/rossmelbourne/ml-agents-master/ml-agents/unity-environment/Assets/ML-Agents/Scripts/Academy.cs:507

**Comment by akmadian** [comment]
As far as I know, you can only interact with an environment if the brain is set to external. If you only need the observations, you may be able to experiment with catching and ignoring any exceptions that come up.

**Comment by vincentpierre** [comment]
Ok, Here is a what I think is a fix : In `unity-environment/Assets/ML-Agents/Scripts/ExternalCommunicator.cs` replace line `287` : 
```csharp
    /// Contains logic for coverting texture into bytearray to send to 
    /// external agent.
    private byte[] TexToByteArray(Texture2D tex)
    {
        byte[] bytes = tex.EncodeToPNG();
        //Object.DestroyImmediate(tex);     <-- Comment this line
        //Resources.UnloadUnusedAssets();   <-- Comment this line
        return bytes;
    }
```
Please let us know how that went.

**Comment by RossMelbourne** [comment]
@vincentpierre Yes, that worked!  Thank you!

**Comment by xiaomaogy** [comment]
@vincentpierre Have you merged this fix? May I close this issue?

**Comment by vincentpierre** [comment]
@xiaomaogy  I have not, that is because there might be some unintended consequences commenting those lines. I do not know if it could cause issues for intensive image based scenarios. The issue should be resolved on the `develop-communicator-redesign` branch since the image collection code changed.

**Comment by xiaomaogy** [comment]
@vincentpierre Ok, I will keep this open and revisit it once your communicator branch has merged.

**Comment by animaleja32** [comment]
My brain Type is set to External, but I still get this error: `WARNING:unityagents: No External Brains found in the Unity Environment. You will not be able to pass actions to your agent(s).`

Am I missing any other settings?

**Comment by xiaomaogy** [comment]
@animaleja32 Can you post a separate issue regarding this and give more information like @RossMelbourne did? I am going to close this issue.

**Comment by xiaomaogy** [comment]
Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.
